//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Dataa
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public int Id { get; set; }
        public int ProductsId { get; set; }
        public int PartnerNameId { get; set; }
        public string Count { get; set; }
        public System.DateTime DateSold { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
