//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Dataa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }
    
        public int PartnersId { get; set; }
        public Nullable<int> PartnerTypeId { get; set; }
        public string PartnersName { get; set; }
        public int PartnersDirectorId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int IndexId { get; set; }
        public int RegionId { get; set; }
        public int CityId { get; set; }
        public int StreetId { get; set; }
        public int HomeId { get; set; }
        public string Inn { get; set; }
        public int Raiting { get; set; }
    
        public virtual City City { get; set; }
        public virtual DirectorPartner DirectorPartner { get; set; }
        public virtual Home Home { get; set; }
        public virtual Index Index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
        public virtual Region Region { get; set; }
        public virtual Street Street { get; set; }
        public virtual TypePartner TypePartner { get; set; }
    }
}
